### PR TITLE
Fix Kramdown issues for task descriptions

### LINKED ISSUE #1095: Quotes in ProFormA Description are escaped
Importing a ProFormA task containing quotes in the description generally works. However, those quotes are shown / stored escaped in CodeHarbor:

Bildschirmfoto 2023-11-17 um 13 15 46

The XML just contains regular quotes:

```xml
<description><![CDATA[<p>
Schreiben Sie ein Programm, das "Hello World!" (ohne die Anf&uuml;hrungsstriche) ausgibt. Das Programm soll eine Methode enthalten, welche den String "Hello World!" zur&uuml;ckgibt. Die Klasse soll "HelloWorld" und die Methode soll "greet" hei&szlig;en.
</p>]]></description>
```

Here is a corresponding task: [helloWorld.zip](https://github.com/openHPI/codeharbor/files/13391511/helloWorld.zip)

### PR DESCRIPTION
**Pull request by kkoehn**
fixed kramdown issues:
- escaping quotes while importing tasks (and converting descriptions to markdown)
- adding linebreaks to long descriptions

fixes #1095

### CODE REVIEW

**Review by MrSerth — COMMENTED** [review]
Looks good, thanks! I haven't execute the code (but just read it), since I tested most code changes already separately.

One question remains, though: Do we have some "migration" strategy for all existing CodeHarbor tasks (~750)? Can we just process all relevant tables and update the texts accordingly? Ideally, this would be as simple as re-storing the object (I wouldn't go with any custom regex or so).

**Comment by MrSerth** [comment]
... and, would you mind to prepare another PR for CodeOcean, please? There, we don't need the migration, since that's the source of truth for the descriptions.

File: db/migrate/20240312201146_migrate_task_descriptions_fix_kramdown_quotes.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
+# frozen_string_literal: true
+
+class MigrateTaskDescriptionsFixKramdownQuotes < ActiveRecord::Migration[7.1]
+  def change
+    Task.find_each {|task| task.update(description: fix_kramdown_descriptions(task.description)) }
```
Comment (MrSerth) [inline db/migrate/20240312201146_migrate_task_descriptions_fix_kramdown_quotes.rb:5]: Just raising the question here again: Do we want to be notified about validation errors by using `update!` rather than `update`?

**Review by MrSerth — COMMENTED** [review]
Thanks, works fine for the intended cases (quotes and newlines). For the escaped characters, I noticed that we have further characters that are currently escaped:

```md
Python\_Fort Aufgabe 1.11.3
```

```md
The area of a rectangle (**Rectangle**) is height \* width.
```

```md
For the two lists \["a", "b", "c"\] and \["a", "x", "b"\], the ...
```

These are probably the other entries from the `ESCAPED_CHAR_RE`... 
How shall we proceed here?

**Comment by kkoehn** [comment]
> These are probably the other entries from the `ESCAPED_CHAR_RE`... How shall we proceed here?

Since we don't really want any symbols escape we could of course remove them from the regex resulting in `(\$\$)|^[ ]{0,3}(:)`. I'm not sure what the remaining two cases are trying to cover. (`$$` and `   :`).
Alternatively we could overwrite `convert_text` to just return `el.value` like with the `raw_text` option.

**Comment by MrSerth** [comment]
> > These are probably the other entries from the `ESCAPED_CHAR_RE`... How shall we proceed here?
> 
> Since we don't really want any symbols escape we could of course remove them from the regex resulting in `(\$\$)|^[ ]{0,3}(:)`. I'm not sure what the remaining two cases are trying to cover. (`$$` and ` :`).

Both of these (`$$` and ` :`) are custom extensions to Markdown, the first one (`$$`) also being available in GitHub-flavored Markdown:

- https://kramdown.gettalong.org/syntax.html#math-blocks
- https://kramdown.gettalong.org/syntax.html#definition-lists

> Alternatively we could overwrite `convert_text` to just return `el.value` like with the `raw_text` option.

Probably, that's the best option. So, yes, I would go with this approach. 

<hr>

Your code looks fine so far; the only thing I have left is the migration (which, currently, only fixes quotes, but not the other cases). Is there some good solution available or do I need to check the database manually?

**Review by MrSerth — APPROVED** [review]
Alright, looks good -- thanks! I've tested the migration locally with various examples and think that it's sufficient now. 👍 

Just tackle the linter comment (which we probably need to disable for the respective line) and then feel free to merge ✅.
